# Generated by Django 4.2.3 on 2023-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_categoria_publicaciones_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
