# Generated by Django 4.2.3 on 2023-07-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_alter_publicaciones_creador_del_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='creador_del_posteo',
            new_name='creador',
        ),
    ]
