# Generated by Django 4.2.3 on 2023-07-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0010_remove_publicaciones_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='creador_del_posteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_usuario', to=settings.AUTH_USER_MODEL)),
                ('relacion_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='publicaciones.publicaciones')),
            ],
        ),
    ]
