# Generated by Django 4.2.3 on 2023-07-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_alter_publicaciones_creador_del_posteo_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='relacion_post',
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicaciones'),
        ),
    ]
