# Generated by Django 4.2.3 on 2023-07-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_alter_comentario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='relacion_post',
        ),
    ]
