# Generated by Django 4.2.3 on 2023-07-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0014_rename_post_comentario_relacion_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='relacion_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioso', to='publicaciones.publicaciones'),
        ),
    ]
